spring:
  # 数据源配置
  datasource:
    # 主数据源配置
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test_hz?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      ###### 连接池配置 ######
      # 最大活跃数
      maxActive: 20
      # 初始化数量
      initialSize: 1
      # 最大连接等待超时时间
      maxWait: 60000
      # 最小空闲数
      minIdle: 1
      #配置隔多久进行一次检测(检测可以关闭的空闲连接)
      timeBetweenEvictionRunsMillis: 60000
      #配置连接在池中的最小生存时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j

    # 从数据源配置
    cluster:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test_hz_city?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      ###### 连接池配置 ######
      # 最大活跃数
      maxActive: 20
      # 初始化数量
      initialSize: 1
      # 最大连接等待超时时间
      maxWait: 60000
      # 最小空闲数
      minIdle: 1
      #配置隔多久进行一次检测(检测可以关闭的空闲连接)
      timeBetweenEvictionRunsMillis: 60000
      #配置连接在池中的最小生存时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j

# Druid 监控配置
druid:
  monitor:
    username: admin
    password: 123456
    logSlowSql: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  level:
    org.springframework: INFO
    org.springframework.dao: INFO
    org.springframework.data: INFO
    com.hz.learnboot.mybatis: INFO
  file:
    max-size: 20MB
  path: logs
