spring:
  # 数据源配置
  datasource:
    # mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_hz_city?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  # Spring Boot Redis
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒），2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    timeout: 10s
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1s
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
mybatis:
  # 指定mybatis基础配置文件和实体类映射文件地址
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.hz.learnboot.redis.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  level:
    org.springframework: INFO
    org.springframework.dao: INFO
    org.springframework.data: INFO
    com.hz.learnboot.mybatis: INFO
  file: logs/spring-boot-logging.log

server:
  # 设置端口号
  port: 8082
  # path前缀
  servlet.context-path: /api
  # 编码格式
  tomcat.uri-encoding: UTF-8