spring:
  # Druid数据源配置
  datasource:
    druid:
      # mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_hz?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      ###### 连接池配置 ######
      # 最大活跃数
      maxActive: 20
      # 初始化数量
      initialSize: 1
      # 最大连接等待超时时间
      maxWait: 60000
      # 最小空闲数
      minIdle: 1
      #配置隔多久进行一次检测(检测可以关闭的空闲连接)
      timeBetweenEvictionRunsMillis: 60000
      #配置连接在池中的最小生存时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # 监控配置
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter.enabled: true #是否启用StatFilter默认值true
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      web-stat-filter.profile-enable: true

      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet.enabled: true  #是否启用StatViewServlet默认值true
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.login-username: admin # 用户名密码。如果不配置则不需要登录
      stat-view-servlet.login-password: 123456

      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      aop-patterns: # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
        com.hz.learnboot.mybatis.dao..*.*(..)

mybatis:
  # 指定mybatis基础配置文件和实体类映射文件地址
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.hz.learnboot.mybatis.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  offsetAsPageNum: true
  params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql

# 日志
logging:
  level:
    org.springframework: INFO
    org.springframework.dao: INFO
    org.springframework.data: INFO
    com.hz.learnboot.mybatis: INFO
  file: logs/spring-boot-logging.log