# 使用 Spring Boot Redis 默认配置
spring:
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒），2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    timeout: 10s
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1s
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

#    # Redis集群配置
#    cluster:
#      # redis集群ip:port,ip2:port2
#      nodes: 127.0.0.1:6379
#      # 转发次数,一般等于节点数
#      max-redirects: 1