spring:
  # 数据源配置
  datasource:
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_hz?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    ###### 连接池配置 ######
    # 最大活跃数
    maxActive: 20
    # 初始化数量
    initialSize: 1
    # 最大连接等待超时时间
    maxWait: 60000
    # 最大空闲数
    maxIdle: 5
    # 最小空闲数
    minIdle: 1
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    timeBetweenEvictionRunsMillis: 60000
    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# 开启DEBUG模式
debug: true